# Generated by Django 5.0.6 on 2024-08-01 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_address',
        ),
        migrations.AddField(
            model_name='member',
            name='member_email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 20, 59, 41, 399144)),
        ),
    ]
